services:
  amaic-kubenode:
    image: amaic/kubenode
    build:
      context: .
      dockerfile: dockerfile
      args:
        - ARCHITECTURE=${ARCHITECTURE}
        - RUNC_VERSION=${RUNC_VERSION}
        - CNI_VERSION=${CNI_VERSION}
        - CONTAINERD_VERSION=${CONTAINERD_VERSION}
